python run_debug.py \
    --output_dir=./model_pr_test_python \
    --tokenizer_name=microsoft/codebert-base \
    --model_name_or_path=microsoft/codebert-base \
    --do_test \
    --train_data_file=/drive1/cuongtm/hienlt/moe/dataset/moe/pr_sv_no_comment/under/primevul_sven_train_nocmt_under.jsonl \
    --eval_data_file=/drive1/cuongtm/hienlt/moe/dataset/moe/pr_sv_no_comment/under/primevul_sven_val_nocmt_under.jsonl \
    --test_data_file=/drive1/cuongtm/hienlt/moe/dataset/moe/pr_sv_no_comment/under/primevul_sven_test_nocmt_under.jsonl \
    --num_train_epochs 1 \
    --block_size 64 \
    --train_batch_size 8 \
    --eval_batch_size 16 \
    --learning_rate 2e-5 \
    --max_grad_norm 1.0 \
    --seed 123456  2>&1 | tee test_sven_cpp_1_baseline.log